name: Translate README

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Translate README to Simplified Chinese
        uses: dephraiim/translate-readme@main
        with:
          LANG: zh-CN
